spring.application.name=report-generator-api

# Datasource Postgres
spring.datasource.url=${URL_CONNECTION}
spring.datasource.username=${USER_DB}
spring.datasource.password=${PASSWORD_DB}


# Pool Hikari
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.read-only=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
spring.datasource.hikari.connection-test-query=SELECT 1

# SQL init - run schema.sql and data.sql on boot
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/schema.sql
spring.sql.init.data-locations=classpath:db/data.sql

# stop the application if error when starting db
spring.sql.init.continue-on-error=false

# Encoding
spring.sql.init.encoding=UTF-8

spring.transaction.default-timeout=30

# Activate debug mode
logging.level.org.springframework.jdbc.core=DEBUG

server.port=3003